# Generated by Django 4.2 on 2024-09-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=255, unique=True)),
                ('plant_name', models.CharField(max_length=255)),
                ('plant_location', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Information',
                'db_table': 'plant_info',
            },
        ),
        migrations.CreateModel(
            name='StatisticCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Statistic Categories',
                'db_table': 'statistic_category',
            },
        ),
        migrations.CreateModel(
            name='StatisticSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='database.statisticcategory')),
            ],
            options={
                'verbose_name_plural': 'Statistic Sub Categories',
                'db_table': 'statistic_sub_category',
            },
        ),
        migrations.CreateModel(
            name='VizStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_statistics', to='database.plantinfo')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_statistics', to='database.statisticsubcategory')),
            ],
            options={
                'verbose_name_plural': 'Visual Statistics',
                'db_table': 'visual_statistics',
            },
        ),
        migrations.CreateModel(
            name='StatisticsVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_key', models.CharField(max_length=255)),
                ('variable_value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='database.statisticsubcategory')),
            ],
            options={
                'verbose_name_plural': 'Statistic Variables',
                'db_table': 'statistic_variables',
            },
        ),
        migrations.CreateModel(
            name='StatisticSubCategoryLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.language')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Localizations', to='database.statisticsubcategory')),
            ],
            options={
                'verbose_name_plural': 'Statistic Sub Category Localizations',
                'db_table': 'statistic_sub_category_Localization',
                'unique_together': {('sub_category', 'language')},
            },
        ),
        migrations.CreateModel(
            name='StatisticCategoryLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Localizations', to='database.statisticcategory')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.language')),
            ],
            options={
                'verbose_name_plural': 'Statistic Category Localizations',
                'db_table': 'statistic_category_Localization',
                'unique_together': {('category', 'language')},
            },
        ),
    ]
