# Generated by Django 4.2 on 2024-09-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantinfo',
            unique_together={('plant_name', 'plant_location')},
        ),
    ]
