# Generated by Django 4.2 on 2024-09-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_plantinfo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsubcategory',
            name='sub_category_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vizstatistics',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='statisticsubcategory',
            unique_together={('sub_category_id', 'category')},
        ),
    ]
