version: '3.3'

services:
  # core
  external_viz_manager:
    image: wasteant/wasteant:external_viz_manager-ubuntu.22.04
    container_name: external_viz_manager-core
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      args:
        user: ${user}
        userid: ${userid}
        group: ${group}
        groupid: ${groupid}
    networks:
      - internal
    ports:
      - 29051-29055:29051-29055
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/home/$user/src
    user: ${user}

  postgres:
    image: postgres:latest
    container_name: external_viz_manager-postgres
    env_file: .env
    networks:
     - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  internal:
    driver: bridge 

volumes:
  postgres_data: